name: SnowballFight
version: '${version}'
main: dev.johnvinh.snowballfight.SnowballFight
api-version: 1.19
arena:
  world: 'snowballfight'
  corner-1:
    x: 74.0
    y: 1.0
    z: 60.0
  corner-2:
    x: 22.0
    y: 1.0
    z: 10.0